from PyQt5.QtCore import Qt 
from PyQt5.QtWidgets import *
a = QApplication([])
w = QWidget()
w.setWindowTitle('galab')
w.resize(300,300)
v = QVBoxLayout()
h1 = QHBoxLayout()
h2 = QHBoxLayout()
h3 = QHBoxLayout()
t1 = QLabel('galab')
h1.addWidget(t1, alignment=Qt.AlignLeft)
t2 = QLabel('galab')
h1.addWidget(t2, alignment=Qt.AlignRight)
t3 = QLabel('galab')
h2.addWidget(t3, alignment=Qt.AlignLeft)
t4 = QLabel('galab')
h3.addWidget(t4, alignment=Qt.AlignRight)
t5 = QLabel('galab')
h3.addWidget(t5, alignment=Qt.AlignCenter)
v.addLayout(h1)
v.addLayout(h2)
v.addLayout(h3)
w.setLayout(v)
w.setLayout(v)
w.show()
a.exec_()